# Exomiser 15.1.0 runtime configuration for the MVA hackathon.
exomiser.data-directory=/mnt/data/mva-hackathon-2026/exomiser/data
exomiser.hg38.data-version=2512
exomiser.phenotype.data-version=2512
logging.level.com.zaxxer.hikari=ERROR
